EMOJI_KEYWORDS = {
    'mexican': ':flag-mx:',
    'japanese': ':flag-jp:',
    'chinese': ':flag-cn:',
    'healthy': ':carrot:',
    'indian': ':flag-in:',
    'korean': ':flag-kr:',
    'thai': ':flag-th:',
    'vietnamese': ':flag-vn:',
    'sushi': ':sushi:',
    'vegetarian': ':onion:',
    'cheese': ':cheese_wedge:',
    'bacon': ':bacon:',
    'chicken': ':chicken:',
    'burger': ':hamburger: :cheezburger:',
    'salad': ':green_salad:',
    'beef': ':cow:',
    'fish': ':fish:',
    'pizza': ':pizza:',
}

GREETINGS = [
    "What's for lunch, you ask?",
    "You like eating, right?",
    "LUNCH?!?",
    "It seems you require sustenance in order to do your job. :thinking_face:",
    "Am I Ops Jeremy, or am I a lunch menu machine?",
    "This ain't Boston proper, but there is decent food around here.",
    "I'm just a poor slackbot from a poor family. But you want lunch, right?",
    ":cyclone: FORECASTED FOODBLOBS. :cyclone:",
    "Hello. I love you. It's almost lunch time.",
    ":partyparrot: I LOVE FOOD. DO YOU LOVE FOOD?! :partyparrot:",
    "Upcoming MBTA passes are now available on the - JUST KIDDING! FOOD!",
    "Thine Lunch Options, Great Shoobxr",
]
